### PR TITLE
(feature) gvm support .go-version and .go-pkgset, similar to rvm

### PR DESCRIPTION
**Pull request by keonjeo**

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Wow, this is a lot to go through but looks awesome so far.  @keonjeo Thank you for all the work you put into this.  Hopefully the maintainers approve!

**Comment by keonjeo** [comment]
@BenKnigge  hi, cloud you help me review this pr. thx

**Comment by alculquicondor** [comment]
It looks like the kubernetes project has had a `.go-version` file for a while https://github.com/kubernetes/kubernetes/pull/114660

However, it doesn't doesn't match the regex `gox.y.z`. It's just `x.y.z`.
As a result, I get the following error in my command line each time I open the repo:

```
Unrecognized command line argument: ''
```

Could both formats be supported?

**Comment by jpbetz** [comment]
The fact that this feature is undocumented and produces console noise when used on the kubernetes repo is really unfortunate. Could this be fixed?

**Pull request merged**
