### PR TITLE
Fixed installer issue: macOS Catalina and later uses zsh as default

### PR DESCRIPTION
**Pull request by bryonbaker**

### CODE REVIEW

**Comment by MattSainz** [comment]
Just tried this locally. Not super knowledgeable about how all this profile information is set up but `id -F` is different from my actual user name (my machine was set up my my it department so unsure if this common) to get this to work though I was able to use `finger $(id -u -n)`

**Comment by bryonbaker** [comment]
I created a pull request with the fix

**Comment by bryonbaker** [comment]
That is very strange:

```
bryon:~$ finger $(id -u -n)
Login: bryon          			Name: Bryon
Directory: /Users/bryon             	Shell: /bin/zsh
On since Tue  8 Feb 09:37 (AEDT) on console, idle 0:06 (messages off)
On since Tue  8 Feb 09:43 (AEDT) on ttys000
No Mail.
No Plan.
bryon:~$ finger $(id -F)
Login: bryon          			Name: Bryon
Directory: /Users/bryon             	Shell: /bin/zsh
On since Tue  8 Feb 09:37 (AEDT) on console, idle 0:06 (messages off)
On since Tue  8 Feb 09:43 (AEDT) on ttys000
No Mail.
No Plan.
```

**Comment by bryonbaker** [comment]
See pull request #399

**Pull request merged**
